<?php return array(
    'root' => array(
        'name' => 'woosa/woosa-plugin',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '3c1383ab214fbc8a062c21b28dfdca6d2792011c',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'rakit/validation' => array(
            'pretty_version' => 'v1.4.0',
            'version' => '1.4.0.0',
            'reference' => 'ff003a35cdf5030a5f2482299f4c93f344a35b29',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rakit/validation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/abstract' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => 'f8d87f6c98a2be306e7a3474a5c3418003bb39a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/abstract',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/action-bulker' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'reference' => 'c3aa65068d3dc7848f425593be19d8c5246d883a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/action-bulker',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/action-scheduler' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => 'cc83ecacceb863046c2c32f8cb53b3c67371a397',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/action-scheduler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/authorization' => array(
            'pretty_version' => '3.4.0',
            'version' => '3.4.0.0',
            'reference' => '859b6e55d8d5990c3b91ffcb2418aac3d0b94128',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/authorization',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/category-mapping' => array(
            'pretty_version' => '2.4.0',
            'version' => '2.4.0.0',
            'reference' => 'd6541004bcc8e227291f1dc7eab57a7362f99eb4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/category-mapping',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/category-selection' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => '8a180fcb4f4275b3a86f2a79efe2a550274f7b45',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/category-selection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/change-tracker' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'reference' => '21b2c9c68ee4a0714e183874fe3603b343da1882',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/change-tracker',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/core' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '2ff74a4e306a0bd90b51f84c9b661cdf1f7d19c1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/core',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/dependency' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'reference' => '4fdbe86f64c248eb83a01de2c49e72058d1067cd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/dependency',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/field-generator' => array(
            'pretty_version' => '1.9.0',
            'version' => '1.9.0.0',
            'reference' => 'a0ede7aefce3128024bb551759d4ba56525238b9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/field-generator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/heartbeat' => array(
            'pretty_version' => '4.1.0',
            'version' => '4.1.0.0',
            'reference' => 'ef5a37f37f07cc09b53082786e73aa8614da63e3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/heartbeat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/interface' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'b27944c3537127a4759e1143cb89a01232f43a91',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/interface',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/logger' => array(
            'pretty_version' => '3.2.2',
            'version' => '3.2.2.0',
            'reference' => '07457b73ddc825e4dad8e32ff533f35a4eb3d2f2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/logger',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/marketplace' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '3b6e4ccea8aa3e61b6dd63ca5804076eae052c58',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/marketplace',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/meta' => array(
            'pretty_version' => '2.4.1',
            'version' => '2.4.1.0',
            'reference' => '78e016a14d3dbe9a36bb8955800fa9f844a96cbd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/meta',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/midlayer' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'reference' => '2d1f2c46c0baa8b8bfeeb2e5d7a863c0a8497418',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/midlayer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/midlayer-oauth' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '3991d558537988922bd0af973f37747f99b5585b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/midlayer-oauth',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/option' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'd7882ffbec9165926cea0e932af154c2beece7ee',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/option',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/order-column-status' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => '5465b460bcda22d715862ea61136df185fa09c1d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/order-column-status',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/order-details' => array(
            'pretty_version' => '1.5.4',
            'version' => '1.5.4.0',
            'reference' => '8db6e94063ba3a776c5071311dbf66c92adf71f0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/order-details',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/order-task' => array(
            'pretty_version' => '1.3.3',
            'version' => '1.3.3.0',
            'reference' => '17986505220f11fd7a67d5a511d9b1659a411199',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/order-task',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/product-column-status' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'reference' => '66fe3ce5cbaca08732da280dbb58be2245b26c91',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/product-column-status',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/product-data-tab' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'd2085c01603b1bfdbf83487d227e8a09e61fd660',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/product-data-tab',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/product-task' => array(
            'pretty_version' => '1.4.3',
            'version' => '1.4.3.0',
            'reference' => '58e1e9633c1f34b71d4e984665e325141638c82b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/product-task',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/request' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'reference' => '23b19c6bd4649d1ac385bc10134093ff2da09425',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/request',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/resource-usage' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '86ca3b50c63c74d1c81d0f347b1e5083cabac089',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/resource-usage',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/settings' => array(
            'pretty_version' => '2.6.0',
            'version' => '2.6.0.0',
            'reference' => '5d8d6edddad48c8d8a565da20bfe984ab033b5fa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/settings',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/support-chat' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '134d5301b8ce0660596ed4d531659ba6e9ac53bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/support-chat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/synchronization' => array(
            'pretty_version' => '2.4.1',
            'version' => '2.4.1.0',
            'reference' => 'dfae2ce67c6c50700ec2156ec3480ba2e63326b3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/synchronization',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/table-column' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '19df80325e468eaac68a199b84e1ef3866a28f2e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/table-column',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/task' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '591744a55546b7173458a6ddea89922761d6a087',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/task',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/term' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '37a1ce4f74cf3cf3407cc333dc13aca8615fb085',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/term',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/third-party' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '4d2285f51bade491a3d0dca3111005d4869504b8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/third-party',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/tools' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => 'fc95b3bd4436dbcbea9e7455a86b5a094abfa0ed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/tools',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/user-task' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => 'cf7d06ac38c5cf06f801091d967c93bfac4155c5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/user-task',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/util' => array(
            'pretty_version' => '1.17.1',
            'version' => '1.17.1.0',
            'reference' => '196cc48a52a5e041b56ec94c7cdc356cc6ce4d11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/util',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/woosa-plugin' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '3c1383ab214fbc8a062c21b28dfdca6d2792011c',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woosa/worker' => array(
            'pretty_version' => '3.2.3',
            'version' => '3.2.3.0',
            'reference' => '9606d1e3499871161bfbbf3adfc35bfe25ca2292',
            'type' => 'library',
            'install_path' => __DIR__ . '/../woosa/worker',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
